name: newproject
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  provider: ^6.1.2
  equatable: ^2.0.7
  http: ^1.3.0
  retrofit: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  retrofit_generator: ^8.0.6

flutter:

  uses-material-design: true


